web/cubingmexico/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.sitemaps.views import sitemap
from .sitemaps import *

sitemaps = {
    'about': StaticViewSitemap,
    'stateteam': StateTeamSitemap,
    'recordsgender': RecordsViewGenderSitemap,
    'recordsgenderstate': RecordsViewGenderStateSitemap,
    'competitionsstate': CompetitionsStateSitemap,
    'personsstate': PersonsStateSitemap,
    'rankingsgender': RankingsViewGenderSitemap,
    'rankingsgenderstate': RankingsViewGenderStateSitemap,
    'sorviewgender': SORViewGenderSitemap,
    'sorviewgenderstate': SORViewGenderStateSitemap,
    'kinchviewgender': KinchViewGenderSitemap,
}

urlpatterns = [
    path("", include("cubingmexico_web.urls", namespace='cubingmexico_web')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),
]

web/cubingmexico_web/urls.py
from django.urls import path

from .views import *

app_name = 'cubingmexico_web'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('about/', AboutView.as_view(), name='about'),
    path('development/', DevelopmentView.as_view(), name='development'),
    path('donations/', DonationsView.as_view(), name='donations'),
    path('completed/', DonationCompletedView.as_view(), name='donation_completed'),
    path('cancel/', DonationCancelView.as_view(), name='donation_cancel'),
    path('documents/', DocumentsView.as_view(), name='documents'),
    path('logo/', LogoView.as_view(), name='logo'),
    path('faq/', FAQView.as_view(), name='faq'),
    path('competitions/', CompetitionsView.as_view(), name='competitions'),
    path('competitions/<str:state>/', CompetitionsView.as_view(), name='competitions'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('person/<str:wca_id>/', MyResultsView.as_view(), name='my_results'),
    path('persons/', PersonsView.as_view(), name='persons'),
    path('persons/<str:state>/', PersonsView.as_view(), name='persons'),
    path('rankings/<str:gender>/<str:event_type>/<str:ranking_type>/', RankingsView.as_view(), name='rankings'),
    path('rankings/<str:gender>/<str:event_type>/<str:ranking_type>/<str:state>/', RankingsView.as_view(), name='rankings'),
    path('records/<str:gender>/', RecordsView.as_view(), name='records'),
    path('records/<str:gender>/<str:state>/', RecordsView.as_view(), name='records'),
    # path('records/<str:include_excluded_events>/', RecordsView.as_view(), name='records'),
    # path('records/<str:state>/<str:include_excluded_events>/', RecordsView.as_view(), name='records'),
    path('sor/<str:ranking_type>/', SORView.as_view(), name='sor'),
    path('sor/<str:ranking_type>/<str:state>/', SORView.as_view(), name='sor'),
    path('kinch/', KinchView.as_view(), name='kinch'),
    path('kinch/<str:state>/', KinchView.as_view(), name='kinch'),
    path('teams/', StateTeamsView.as_view(), name='state_teams'),
    path('team/<str:team_code>/', IndividualStateTeamView.as_view(), name='team'),
    path('team/<str:team_code>/edit/', EditStateTeamView.as_view(), name='edit_team'),
    path('team/<str:team_code>/add_member/', AddStateTeamMemberView.as_view(), name='add_member'),
    path('team/<str:team_code>/remove_member/<int:pk>/', RemoveStateTeamMemberView.as_view(), name='remove_member'),
    path('cubingmexico_wca/callback/', WCACallbackView.as_view(), name='wca_callback'),
    # path('api-endpoint/', StateTeamEndpointView.as_view(), name='state_team_endpoint_view'),
]

web/templates/includes/faq.html
<div class="accordion mt-3" id="accordionExample">
  <h1 class="fs-3 my-3">Preguntas frecuentes</h1>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        <strong>¿Por qué no aparezco como miembro del team? :(</strong>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        Si no apareces como miembro del team es porque no has participado en una competencia oficial de la <a href="https://www.worldcubeassociation.org/" class="text-decoration-none">World Cube Association</a> o porque no has sido agregado por algún administrador, recuerda que todos pueden ser parte de un team, el único requisito es que vivas en el mismo estado, si cumples con lo anterior mencionado contáctate con el team en alguno de los medios que aparecen <a href="{% url 'cubingmexico_web:team' team_code=selected_state %}" class="text-decoration-none">aquí</a> para que puedan agregarte.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        <strong>¿Por qué aparece tal persona en este team si ni siquiera vive en este estado?</strong>
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        Puede deberse a que la persona se cambió recientemente de residencia o simplemente a algún error del administrador de un team, puedes enviar un mensaje a alguna de sus <a href="{% url 'cubingmexico_web:team' team_code=selected_state %}" class="text-decoration-none">redes sociales</a> para que puedan revisarlo.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        <strong>Vivo en este estado pero no quiero pertenecer al team, ¿qué puedo hacer?</strong>
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        Para poder aparecer en los rankings y récords estatales sin tener que ser miembro de un team tienes que hacer lo siguiente:
        <ol>
          <li>Haber participado en una competencia oficial avalada por la <a href="https://www.worldcubeassociation.org/" class="text-decoration-none">World Cube Association</a>.</li>
          {% if not user.is_authenticated %}
          <li><a href="{{ wca_login_uri }}" class="text-decoration-none">Iniciar sesión en Cubing México</a> utilizando tus credenciales de la WCA.</li>
          {% else %}
          <li>Iniciar sesión en Cubing México utilizando tus credenciales de la WCA.</li>
          {% endif %}
          {% if user.cubingmexicoprofile.person_state_team %}
          <li>Ir a tu <a href="{% url 'cubingmexico_web:my_results' wca_id=request.user.wcaprofile.wca_id %}" class="text-decoration-none">Perfil</a> y seleccionar tu estado.</li>
          {% else %}
          <li>Ir a tu Perfil y seleccionar tu estado.</li>
          {% endif %}
        </ol>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
        <strong>Ya hice todo lo mencionado anteriormente y no aparezco en los resultados de mi estado</strong>
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        Si has completado las acciones mencionadas previamente y aún no ves resultados, se debe a que la base de datos aún no ha sido actualizada. Esto es una situación común y no debes inquietarte. La base de datos se actualiza todos los días a las 02:00 UTC-6 (2 AM hora de la Ciudad de México). Te pedimos amablemente que tengas paciencia y compruebes de nuevo mañana.
      </div>
    </div>
  </div>
</div>

web/templates/includes/footer.html
{% load static %}

<footer class="footer mt-auto py-3">
  <div class="container">
    <div class="row">
      <div class="col-9">
        <span class="text-muted">¿Ves algo erróneo o tienes alguna sugerencia? Repórtalo en el repositorio de <a href="https://github.com/LeonardoSDT/cubingmexico" class="text-body text-decoration-none">Cubing México <i class="bi bi-github"></i></a></span>
        <br>
        <span class="text-muted fw-lighter">Últimos resultados: {{ last_competition.name }}</span>
          {% if missing_competitions %}
          <br>
          <span class="text-muted fw-lighter">Resultados pendientes:</span>
          <ul>
            {% for missing_competition in missing_competitions %}
              <li class="text-muted fw-lighter">{{ missing_competition.name }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>
      <div class="col-3">
        <div class="form-check form-switch m-3">
          <label class="form-check-label" for="flexSwitchCheckChecked">
            <input class="form-check-input p-2" type="checkbox" role="switch" id="flexSwitchCheckChecked" name="flexSwitchCheckChecked" aria-labelledby="flexSwitchCheckChecked" onclick="toggleDarkMode()">
            <i class="bi bi-sun-fill" id="sunIcon"></i>
            <i class="bi bi-moon-fill" id="moonIcon" style="display: none;"></i>
          </label>
        </div>
      </div>
    </div>
    <div class="row">
      <ul class="nav list-unstyled d-flex">
        <li class="ms-3"><a class="text-body" href="https://www.facebook.com/CubingMexico" aria-label="Enlace de Facebook"><i class="bi bi-facebook m-1"></i></a></li>
        <li class="ms-3"><a class="text-body" href="https://www.instagram.com/cubingmexico/" aria-label="Enlace de Instagram"><i class="bi bi-instagram m-1"></i></a></li>
      </ul>
    </div>    
  </div>
</footer>

web/templates/includes/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'cubingmexico_web:index' %}"><img src="{% static 'img/cubingmexico_logo.svg' %}" width="50" height="50" alt="Logo de Cubing México" class="me-2">Cubing México</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cubingmexico_web:competitions' %}"><i class="bi bi-trophy-fill me-2"></i>Competencias</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink2" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-list-ol me-2"></i>Resultados</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
            <li><a class="dropdown-item" href="{% url 'cubingmexico_web:rankings' event_type='333' ranking_type='single' gender='a' %}"><i class="bi bi-reception-4 me-2"></i>Rankings</a></li>
            <li><a class="dropdown-item" href="{% url 'cubingmexico_web:records' gender='a' %}"><i class="bi bi bi-award-fill me-2"></i>Récords</a></li>
            <li><a class="dropdown-item" href="{% url 'cubingmexico_web:persons' %}"><i class="bi bi-people-fill me-2"></i>Personas</a></li>
            <li><a class="dropdown-item" href="{% url 'cubingmexico_web:sor' ranking_type='single' %}"><i class="bi bi-plus-circle-fill me-2"></i>SOR</a></li>
            <li><a class="dropdown-item" href="{% url 'cubingmexico_web:kinch' state='JAL' %}"><i class="bi bi-bar-chart-steps me-2"></i>Kinch Ranks</a></li>
            <!-- <li><a class="dropdown-item disabled" href="#"><i class="bi bi-trophy me-2"></i>UNRs</a></li> -->
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cubingmexico_web:state_teams' %}"><i class="bi bi-people-fill me-2"></i>Teams estatales</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink3" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-file-person-fill me-2"></i>Acerca de</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink3">
            <li><a class="dropdown-item" href="{% url 'cubingmexico_web:about' %}"><i class="bi bi-info-circle-fill me-2"></i>Acerca de</a></li>
            <!-- <li><a class="dropdown-item" href="{% url 'cubingmexico_web:development' %}"><i class="bi bi-braces me-2"></i>Desarrollo</a></li> -->
            <li><a class="dropdown-item" href="{% url 'cubingmexico_web:donations' %}"><i class="bi bi-cash me-2"></i>Donaciones</a></li>
            <li><a class="dropdown-item" href="{% url 'cubingmexico_web:faq' %}"><i class="bi bi-question-circle-fill me-2"></i>Preguntas frecuentes</a></li>
            <li><a class="dropdown-item" href="{% url 'cubingmexico_web:logo' %}"><i class="bi bi-image me-2"></i>Logo</a></li>
          </ul>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item dropdown me-5">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink4" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-person-fill me-2"></i>{{ user.wcaprofile }}</a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink4">
                <li><a class="dropdown-item" href="{% url 'cubingmexico_web:profile' %}"><i class="bi bi-person-lines-fill me-2"></i>Perfil</a></li>
                <li><a class="dropdown-item" href="{% url 'cubingmexico_web:my_results' wca_id=request.user.wcaprofile.wca_id %}"><i class="bi bi-table me-2"></i>Mis resultados</a></li>
                {% if user.cubingmexicoprofile.person_state_team %}
                <li><a class="dropdown-item" href="{% url 'cubingmexico_web:team' team_code=request.user.cubingmexicoprofile.person_state_team.state_team.state.three_letter_code %}"><i class="bi bi-people-fill me-2"></i>Mi team</a></li>
                {% endif %}
                <li><a class="dropdown-item" href="{% url 'cubingmexico_web:logout' %}"><i class="bi bi-box-arrow-right me-2"></i>Cerar sesión</a></li>
              </ul>
          </li>
          {% else %}
          <li class="nav-item">
              <a class="nav-link" href="{{ wca_login_uri }}"><i class="bi bi-box-arrow-in-left me-2"></i>Iniciar sesión con la WCA</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>