web/cubingmexico/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.sitemaps.views import sitemap
from .sitemaps import *

sitemaps = {
    'about': StaticViewSitemap,
    'stateteam': StateTeamSitemap,
    'recordsgender': RecordsViewGenderSitemap,
    'recordsgenderstate': RecordsViewGenderStateSitemap,
    'competitionsstate': CompetitionsStateSitemap,
    'personsstate': PersonsStateSitemap,
    'rankingsgender': RankingsViewGenderSitemap,
    'rankingsgenderstate': RankingsViewGenderStateSitemap,
    'sorviewgender': SORViewGenderSitemap,
    'sorviewgenderstate': SORViewGenderStateSitemap,
    'kinchviewgender': KinchViewGenderSitemap,
}

urlpatterns = [
    path("", include("cubingmexico_web.urls", namespace='cubingmexico_web')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),
]

web/cubingmexico_web/urls.py
from django.urls import path

from .views import *

app_name = 'cubingmexico_web'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('about/', AboutView.as_view(), name='about'),
    path('development/', DevelopmentView.as_view(), name='development'),
    path('donations/', DonationsView.as_view(), name='donations'),
    path('completed/', DonationCompletedView.as_view(), name='donation_completed'),
    path('cancel/', DonationCancelView.as_view(), name='donation_cancel'),
    path('documents/', DocumentsView.as_view(), name='documents'),
    path('logo/', LogoView.as_view(), name='logo'),
    path('faq/', FAQView.as_view(), name='faq'),
    path('competitions/', CompetitionsView.as_view(), name='competitions'),
    path('competitions/<str:state>/', CompetitionsView.as_view(), name='competitions'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('person/<str:wca_id>/', MyResultsView.as_view(), name='my_results'),
    path('persons/', PersonsView.as_view(), name='persons'),
    path('persons/<str:state>/', PersonsView.as_view(), name='persons'),
    path('rankings/<str:gender>/<str:event_type>/<str:ranking_type>/', RankingsView.as_view(), name='rankings'),
    path('rankings/<str:gender>/<str:event_type>/<str:ranking_type>/<str:state>/', RankingsView.as_view(), name='rankings'),
    path('records/<str:gender>/', RecordsView.as_view(), name='records'),
    path('records/<str:gender>/<str:state>/', RecordsView.as_view(), name='records'),
    # path('records/<str:include_excluded_events>/', RecordsView.as_view(), name='records'),
    # path('records/<str:state>/<str:include_excluded_events>/', RecordsView.as_view(), name='records'),
    path('sor/<str:ranking_type>/', SORView.as_view(), name='sor'),
    path('sor/<str:ranking_type>/<str:state>/', SORView.as_view(), name='sor'),
    path('kinch/', KinchView.as_view(), name='kinch'),
    path('kinch/<str:state>/', KinchView.as_view(), name='kinch'),
    path('teams/', StateTeamsView.as_view(), name='state_teams'),
    path('team/<str:team_code>/', IndividualStateTeamView.as_view(), name='team'),
    path('team/<str:team_code>/edit/', EditStateTeamView.as_view(), name='edit_team'),
    path('team/<str:team_code>/add_member/', AddStateTeamMemberView.as_view(), name='add_member'),
    path('team/<str:team_code>/remove_member/<int:pk>/', RemoveStateTeamMemberView.as_view(), name='remove_member'),
    path('cubingmexico_wca/callback/', WCACallbackView.as_view(), name='wca_callback'),
    # path('api-endpoint/', StateTeamEndpointView.as_view(), name='state_team_endpoint_view'),
]

web/cubingmexico_web/forms.py
from django.forms import ModelForm
from django import forms

from .models import CubingmexicoProfile, State, StateTeam, PersonStateTeam
from cubingmexico_wca.models import Person
from phonenumber_field.formfields import PhoneNumberField


class CubingmexicoProfileForm(forms.ModelForm):
    class Meta:
        model = CubingmexicoProfile
        fields = ['state']

    state = forms.ModelChoiceField(
        queryset=State.objects.all(),
        empty_label="Selecciona una opción",
        widget=forms.Select(attrs={'class': 'form-control'})
        )

class StateTeamForm(forms.ModelForm):
    class Meta:
        model = StateTeam
        fields = ['name', 'description', 'team_logo', 'facebook_link', 'instagram_link', 'phone_number', 'email']

    name = forms.CharField(
        max_length=255,
        label="Nombre del Team *",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    description = forms.CharField(
        label="Descripción del Team",
        widget=forms.Textarea(attrs={'class': 'form-control'}),
        required=False
    )
    team_logo = forms.ImageField(
        widget=forms.FileInput(attrs={'class': 'form-control'}),
        label="Logotipo del Team",
        required=False
    )
    facebook_link = forms.CharField(
        max_length=255,
        label="Enlace a Facebook",
        widget=forms.URLInput(attrs={'class': 'form-control'}),
        required=False
    )
    instagram_link = forms.CharField(
        max_length=255,
        label="Enlace a Instagram",
        widget=forms.URLInput(attrs={'class': 'form-control'}),
        required=False
    )
    phone_number = PhoneNumberField(
        label="Número de teléfono",
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        required=False
    )
    email = forms.EmailField(
        max_length=255,
        label="Dirección de correo electrónico",
        widget=forms.EmailInput(attrs={'class': 'form-control'}),
        required=False
    )


class PersonStateTeamForm(forms.ModelForm):
    class Meta:
        model = PersonStateTeam
        fields = ['person']

    person = forms.ModelChoiceField(
        queryset=Person.objects.all(),
        empty_label="Selecciona una persona",
        label="Persona",
        widget=forms.Select(attrs={'class': 'form-control'})
        )

web/templates/pages/teams/add_member.html
{% extends 'base.html' %}

{% block title %}Añadir miembro a {{ state }}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css">

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock stylesheets %}

{% block content %}

<h1 class="my-3">Añadir miembro a {{ state }}</h1>

<div class="row">
    <div class="col-12 mb-3">
        <div class="card">
            <div class="card-header text-center">
                <h4>Añadir miembro</h4>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success"><i class="bi bi-check-lg me-2"></i>Añadir</button>
                    <a href="{% url 'cubingmexico_web:team' team_code=state.three_letter_code %}" class="btn btn-danger"><i class="bi bi-x-lg me-2"></i>Cancelar</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block javascripts %}
<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
        $('#id_person').select2();
    });
</script>
{% endblock javascripts %}

web/templates/pages/teams/edit_team.html
{% extends 'base.html' %}

{% block title %}Editar {{ object.name }} - Cubing México{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css">
{% endblock stylesheets %}

{% block content %}

<h1 class="my-3">Editar {{ object.name }}</h1>

<div class="row">
    <div class="col-12 mb-3">
        <div class="card">
            <div class="card-header text-center">
                <h4>Información del team</h4>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success"><i class="bi bi-check-lg me-2"></i>Guardar</button>
                    <a href="{% url 'cubingmexico_web:team' team_code=object.state.three_letter_code %}" class="btn btn-danger"><i class="bi bi-x-lg me-2"></i>Cancelar</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

web/templates/pages/teams/remove_member.html
{% extends 'base.html' %}

{% block title %}¿Desea eliminar a {{ object.person.name }} de {{ object.state_team }}? - Cubing México{% endblock %}

{% block stylesheets %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock stylesheets %}

{% block content %}

<h1 class="my-3">Eliminar miembro</h1>

<div class="row">
    <div class="col-12 mb-3">
        <div class="card">
            <div class="card-header text-center">
                <h4>¿Desea eliminar a {{ object.person.name }} de {{ object.state_team }}?</h4>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success"><i class="bi bi-check-lg me-2"></i>Confirmar</button>
                    <a href="{% url 'cubingmexico_web:team' team_code=state.three_letter_code %}" class="btn btn-danger"><i class="bi bi-x-lg me-2"></i>Cancelar</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block javascripts %}
<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
        $('#id_person').select2();
    });
</script>
{% endblock javascripts %}

web/templates/pages/teams/teams.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Teams estatales - Cubing México{% endblock %}

{% block meta_title %}Teams estatales - Cubing México{% endblock %}
{% block meta_type %}website{% endblock %}
{% block meta_url %}https://cubingmexico.net/teams/{% endblock %}
{% block meta_image %}{% static 'img/cubingmexico_logo.png' %}{% endblock %}

{% block meta_description %}Explora los teams o equipos estatales de speedcubing en México y descubre los speedcubers más destacados. Conoce más sobre la comunidad del cubo Rubik en México.{% endblock %}
{% block meta_keywords %}equipos, speedcubing, cubo Rubik, México, jugadores, competencias, teams, estados{% endblock %}

{% block content %}

<h1 class="text-center my-3">Teams estatales</h1>

<div class="card mb-3">
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>"Los teams, esa gente que por placer se reúnen en plazas, que se contagian de entusiasmo al mirar los logros de sus miembros, que empujan a otros y que en conjunto comparten su pasión por el speedcubing."</p>
        <footer class="blockquote-footer">Aru Gordillo, <cite title="Source Title">Delegada de la WCA en México</cite></footer>
      </blockquote>
    </div>
</div>

<div class="container">
    <div class="row">
        {% if state_teams %}
            {% for team in state_teams %}
            <div class="col-lg-4 d-flex align-items-stretch text-center mb-3">
                <div class="card mx-auto" style="width: 18rem;">
                    {% if team.team_logo %}
                        <img src="{{ team.team_logo.url }}" class="card-img-top" alt="Logotipo de {{ team.name }}">
                    {% else %}
                        <img src="" class="card-img-top" alt="Logotipo de {{ team.name }}">
                    {% endif %}
                    <div class="card-body">
                    <h2 class="card-title fs-5">{{ team.name }}</h2>
                    <p class="card-text">{{ team.description|truncatewords:20 }}</p>
                    <p class="card-text"><strong>Estado:</strong> {{ team.state }}</p>
                    <p class="card-text"><strong>Miembros:</strong> {{ team.person_count }}</p>
                    <a href="{% url 'cubingmexico_web:team' team_code=team.state.three_letter_code %}" class="btn btn-primary"><i class="bi bi-people-fill me-2"></i>Ver team</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% endif %}
    </div>
</div>

{% endblock %}